/**
 * @file src/opencl/gpu_kernels.h
 * The OpenCL C source of the decomposition's kernels, as a string the device
 * module compiles twice: once per factor precision.
 *
 * This is a transcription of ``src/core/matrix.inc`` and
 * ``src/core/decomposition_numeric.inc`` onto flat arrays. The arithmetic is
 * deliberately identical -- same loop order, same accumulation types, no
 * pivoting, vectors always double -- so a device factorization agrees with the
 * CPU one to rounding rather than to a different algorithm's rounding. What
 * changes is the addressing: no pointers on a device, so the row and entry
 * structures of a host frame become the prefix arrays every kernel indexes.
 *
 * The two variants differ only in ``scalar``, the type factors are stored in:
 * the single variant accumulates its products in ``float`` exactly as the
 * ``HYBSOL_ACC`` of the CPU's single instantiation does, while the vectors stay
 * double because that is what the solve protocol hands around.
 */

#ifndef HYBSOL_OPENCL_GPU_KERNELS_H
#define HYBSOL_OPENCL_GPU_KERNELS_H

static const char HYBSOL_GPU_KERNEL_SOURCE[] =
    "#pragma OPENCL EXTENSION cl_khr_fp64 : enable\n"
    "\n"
    "/* What hybsol_operation_t calls the two operations. */\n"
    "#define HYBSOL_OP_INVERT_DIAGONAL 0u\n"
    "#define HYBSOL_OP_ELIMINATE 1u\n"
    "\n"
    "#ifdef HYBSOL_GPU_DOUBLE\n"
    "typedef double scalar;\n"
    "#define HYBSOL_NAME(n) hybsol_##n##_f64\n"
    "#else\n"
    "typedef float scalar;\n"
    "#define HYBSOL_NAME(n) hybsol_##n##_f32\n"
    "#endif\n"
    "\n"
    "/* Rows/columns of block idx, from the prefix of block sizes. */\n"
    "static ulong block_size(__global const ulong *off, const ulong idx)\n"
    "{\n"
    "    return off[idx + 1] - off[idx];\n"
    "}\n"
    "\n"
    "/* out = a @ b, in the CPU's i-k-j order. */\n"
    "static void mat_multiply(__global const scalar *a, __global const scalar *b,\n"
    "                         __global scalar *out, const ulong rows, const ulong inner,\n"
    "                         const ulong cols)\n"
    "{\n"
    "    for (ulong i = 0; i < rows; ++i)\n"
    "    {\n"
    "        for (ulong j = 0; j < cols; ++j)\n"
    "            out[i * cols + j] = (scalar)0;\n"
    "\n"
    "        for (ulong k = 0; k < inner; ++k)\n"
    "        {\n"
    "            const scalar aik = a[i * inner + k];\n"
    "            for (ulong j = 0; j < cols; ++j)\n"
    "                out[i * cols + j] = (scalar)(out[i * cols + j] + aik * b[k * cols + j]);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "static void mat_subtract(__global scalar *a, __global const scalar *b,\n"
    "                        const ulong rows, const ulong cols)\n"
    "{\n"
    "    for (ulong i = 0; i < rows * cols; ++i)\n"
    "        a[i] = (scalar)(a[i] - b[i]);\n"
    "}\n"
    "\n"
    "/* Doolittle LU in place, no pivoting: an exactly zero pivot fails. */\n"
    "static int lu_decompose(__global scalar *m, const ulong n)\n"
    "{\n"
    "    for (ulong i = 0; i < n; ++i)\n"
    "    {\n"
    "        for (ulong j = i; j < n; ++j)\n"
    "        {\n"
    "            scalar u_ij = m[i * n + j];\n"
    "            for (ulong k = 0; k < i; ++k)\n"
    "                u_ij = (scalar)(u_ij - m[i * n + k] * m[k * n + j]);\n"
    "            m[i * n + j] = u_ij;\n"
    "        }\n"
    "\n"
    "        const scalar pivot = m[i * n + i];\n"
    "        if (pivot == (scalar)0)\n"
    "            return 1;\n"
    "\n"
    "        for (ulong j = i + 1; j < n; ++j)\n"
    "        {\n"
    "            scalar l_ij = m[j * n + i];\n"
    "            for (ulong k = 0; k < i; ++k)\n"
    "                l_ij = (scalar)(l_ij - m[k * n + i] * m[j * n + k]);\n"
    "            m[j * n + i] = (scalar)(l_ij / pivot);\n"
    "        }\n"
    "    }\n"
    "    return 0;\n"
    "}\n"
    "\n"
    "/* Solve m @ x = b in place on b, one column at a time: the unit\n"
    "   diagonal of L, then both halves of U. Row scaling solves a whole\n"
    "   block, so the number of columns is part of the contract. */\n"
    "static void lu_solve(__global const scalar *m, __global scalar *b, const ulong n,\n"
    "                  const ulong cols)\n"
    "{\n"
    "    for (ulong c = 0; c < cols; ++c)\n"
    "    {\n"
    "        /* Row-major: column c is every cols-th element. */\n"
    "        for (ulong i = 0; i < n; ++i)\n"
    "        {\n"
    "            scalar v = b[i * cols + c];\n"
    "            for (ulong j = 0; j < i; ++j)\n"
    "                v = (scalar)(v - m[i * n + j] * b[j * cols + c]);\n"
    "            b[i * cols + c] = v;\n"
    "        }\n"
    "\n"
    "        for (ulong i = n; i > 0; --i)\n"
    "        {\n"
    "            scalar v = b[(i - 1) * cols + c];\n"
    "            for (ulong j = i; j < n; ++j)\n"
    "                v = (scalar)(v - m[(i - 1) * n + j] * b[j * cols + c]);\n"
    "            b[(i - 1) * cols + c] = (scalar)(v / m[(i - 1) * n + i - 1]);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* out -= a @ b with a in factor storage and b, out double vectors. */\n"
    "static void vec_multiply_sub(__global const scalar *a, __global const double *b,\n"
    "                                __global double *out, const ulong rows, const ulong inner,\n"
    "                                const ulong cols)\n"
    "{\n"
    "    for (ulong i = 0; i < rows; ++i)\n"
    "    {\n"
    "        for (ulong j = 0; j < cols; ++j)\n"
    "        {\n"
    "            scalar v = (scalar)0;\n"
    "            for (ulong k = 0; k < inner; ++k)\n"
    "                v = (scalar)(v + a[i * inner + k] * (scalar)b[k * cols + j]);\n"
    "\n"
    "            out[i * cols + j] -= (double)v;\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Solve m @ x = b with m in factor storage and b, out double: the\n"
    "   narrowed path's accumulation, which is double for both variants. */\n"
    "static void vec_lu_solve(__global const scalar *m, __global double *b, const ulong n)\n"
    "{\n"
    "    for (ulong i = 0; i < n; ++i)\n"
    "    {\n"
    "        double v = b[i];\n"
    "        for (ulong j = 0; j < i; ++j)\n"
    "            v -= (double)m[i * n + j] * b[j];\n"
    "        b[i] = v;\n"
    "    }\n"
    "\n"
    "    for (ulong i = n; i > 0; --i)\n"
    "    {\n"
    "        double v = b[i - 1];\n"
    "        for (ulong j = i; j < n; ++j)\n"
    "            v -= (double)m[(i - 1) * n + j] * b[j];\n"
    "        b[i - 1] = v / (double)m[(i - 1) * n + i - 1];\n"
    "    }\n"
    "}\n"
    "\n"
    "static ulong entry_at(__global const ulong *row_entry_offset,\n"
    "                      __global const ulong *entry_col, const ulong row,\n"
    "                      const ulong slot)\n"
    "{\n"
    "    return row_entry_offset[row] + slot;\n"
    "}\n"
    "\n"
    "/* One elimination: subtract the k-th source row from what is left of row_tgt. */\n"
    "static void eliminate_step(__global const ulong *level_rows,\n"
    "                           __global const ulong *row_n_elim,\n"
    "                           __global const ulong *row_entry_offset,\n"
    "                           __global const ulong *entry_col,\n"
    "                           __global const ulong *entry_val_offset,\n"
    "                           __global const ulong *block_offsets, __global scalar *vals,\n"
    "                           __global scalar *scratch, const ulong row_tgt, const ulong k,\n"
    "                           const ulong max_block)\n"
    "{\n"
    "    const ulong at_tgt = row_entry_offset[row_tgt];\n"
    "    const ulong end_tgt = row_entry_offset[row_tgt + 1];\n"
    "    const ulong entry_k = at_tgt + k;\n"
    "    const ulong col_src = entry_col[entry_k];\n"
    "    const ulong size_tgt = block_size(block_offsets, row_tgt);\n"
    "    const ulong size_src = block_size(block_offsets, col_src);\n"
    "    __global scalar *const mat = vals + entry_val_offset[entry_k];\n"
    "\n"
    "    /* Past the multiplier in the target, past the diagonal in the source: both\n"
    "       are exactly the columns greater than the source's. */\n"
    "    const ulong at_src = row_entry_offset[col_src];\n"
    "    const ulong count_src = row_entry_offset[col_src + 1] - at_src;\n"
    "    ulong a = k + 1;\n"
    "    for (ulong b = row_n_elim[col_src] + 1; b < count_src; ++b)\n"
    "    {\n"
    "        const ulong entry_src = at_src + b;\n"
    "        const ulong col = entry_col[entry_src];\n"
    "        while (a < end_tgt - at_tgt && entry_col[at_tgt + a] < col)\n"
    "            ++a;\n"
    "\n"
    "        const ulong n_cols = block_size(block_offsets, col);\n"
    "        mat_multiply(mat, vals + entry_val_offset[entry_src], scratch, size_tgt, size_src, n_cols);\n"
    "\n"
    "        /* Always a subtraction, never an assignment: a column the target gained\n"
    "           only at this step sits at zero. */\n"
    "        mat_subtract(vals + entry_val_offset[at_tgt + a], scratch, size_tgt, n_cols);\n"
    "        ++a;\n"
    "    }\n"
    "    (void)scratch;\n"
    "    (void)max_block;\n"
    "}\n"
    "\n"
    "/* Scale everything above the diagonal by the inverse of the factors. */\n"
    "static void invert_diagonal_into_row(__global const ulong *row_n_elim,\n"
    "                                     __global const ulong *row_entry_offset,\n"
    "                                     __global const ulong *entry_col,\n"
    "                                     __global const ulong *entry_val_offset,\n"
    "                                     __global const ulong *block_offsets,\n"
    "                                     __global scalar *vals, const ulong row)\n"
    "{\n"
    "    const ulong at = row_entry_offset[row];\n"
    "    const ulong count = row_entry_offset[row + 1] - at;\n"
    "    const ulong i_diag = row_n_elim[row];\n"
    "    const ulong size = block_size(block_offsets, row);\n"
    "    __global const scalar *const diag = vals + entry_val_offset[at + i_diag];\n"
    "    for (ulong i = i_diag + 1; i < count; ++i)\n"
    "    {\n"
    "        __global scalar *const entry = vals + entry_val_offset[at + i];\n"
    "        lu_solve(diag, entry, size, block_size(block_offsets, entry_col[at + i]));\n"
    "    }\n"
    "}\n"
    "\n"
    "/* One pass of the schedule: each work item is one block row of the pass. */\n"
    "__kernel void HYBSOL_NAME(factorize_pass)(__global const ulong *level_rows,\n"
    "                                              __global const ulong *level_k,\n"
    "                                              __global const ulong *row_n_elim,\n"
    "                                              __global const ulong *row_level,\n"
    "                                              __global const ulong *row_entry_offset,\n"
    "                                              __global const ulong *entry_col,\n"
    "                                              __global const ulong *entry_val_offset,\n"
    "                                              __global const ulong *block_offsets,\n"
    "                                              __global scalar *vals, __global scalar *scratch,\n"
    "                                              __global int *fail_j, const ulong pass, const ulong from,\n"
    "                                              const ulong pass_rows, const ulong max_block)\n"
    "{\n"
    "    const ulong j = from + get_global_id(0);\n"
    "    /* Padded to whole work groups; the padding does nothing. The indices\n"
    "       are absolute and pass_rows a count, hence the offset. */\n"
    "    if (j >= from + pass_rows)\n"
    "        return;\n"
    "    const ulong row = level_rows[j];\n"
    "    const ulong step = level_k[j];\n"
    "    (void)level_k;\n"
    "\n"
    "    if (step < row_n_elim[row])\n"
    "        eliminate_step(level_rows, row_n_elim, row_entry_offset, entry_col, entry_val_offset,\n"
    "                      block_offsets, vals, scratch + row * max_block * max_block, row, step,\n"
    "                      max_block);\n"
    "    if (pass == row_level[row])\n"
    "    {\n"
    "        const ulong at = row_entry_offset[row];\n"
    "        const ulong i_diag = row_n_elim[row];\n"
    "        const ulong size = block_size(block_offsets, row);\n"
    "        __global scalar *const diag = vals + entry_val_offset[at + i_diag];\n"
    "        if (lu_decompose(diag, size) != 0)\n"
    "        {\n"
    "            atomic_min(fail_j, (int)j);\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            invert_diagonal_into_row(row_n_elim, row_entry_offset, entry_col, entry_val_offset,\n"
    "                                      block_offsets, vals, row);\n"
    "        }\n"
    "    }\n"
    "    (void)level_rows;\n"
    "}\n"
    "\n"
    "/* The solve's forward substitution: the same passes, one work item per row. */\n"
    "__kernel void HYBSOL_NAME(forward_pass)(__global const ulong *level_rows,\n"
    "                                            __global const ulong *level_k,\n"
    "                                            __global const ulong *row_n_elim,\n"
    "                                            __global const ulong *row_level,\n"
    "                                            __global const ulong *row_entry_offset,\n"
    "                                            __global const ulong *entry_col,\n"
    "                                            __global const ulong *entry_val_offset,\n"
    "                                            __global const ulong *block_offsets,\n"
    "                                            __global const scalar *vals, __global double *vec,\n"
    "                                            const ulong pass, const ulong from,\n"
    "                                            const ulong pass_rows)\n"
    "{\n"
    "    const ulong j = from + get_global_id(0);\n"
    "    /* Padded to whole work groups; the padding does nothing. The indices\n"
    "       are absolute and pass_rows a count, hence the offset. */\n"
    "    if (j >= from + pass_rows)\n"
    "        return;\n"
    "    const ulong row = level_rows[j];\n"
    "    const ulong step = level_k[j];\n"
    "    const ulong at = row_entry_offset[row];\n"
    "    const ulong size_row = block_size(block_offsets, row);\n"
    "\n"
    "    if (step < row_n_elim[row])\n"
    "    {\n"
    "        const ulong entry = at + step;\n"
    "        const ulong col = entry_col[entry];\n"
    "        vec_multiply_sub(vals + entry_val_offset[entry], vec + block_offsets[col],\n"
    "                       vec + block_offsets[row], size_row, block_size(block_offsets, col),\n"
    "                       (ulong)1);\n"
    "    }\n"
    "    if (pass == row_level[row])\n"
    "    {\n"
    "        vec_lu_solve(vals + entry_val_offset[at + row_n_elim[row]], vec + block_offsets[row], size_row);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Back substitution: serial on the CPU, and so one work item here. */\n"
    "__kernel void HYBSOL_NAME(back_substitute)(__global const ulong *row_entry_offset,\n"
    "                                                   __global const ulong *entry_col,\n"
    "                                                   __global const ulong *entry_val_offset,\n"
    "                                                   __global const ulong *block_offsets,\n"
    "                                                   __global const scalar *vals, __global double *vec,\n"
    "                                                   const ulong n)\n"
    "{\n"
    "    if (get_global_id(0) != 0)\n"
    "        return;\n"
    "\n"
    "    for (ulong i = n; i > 0; --i)\n"
    "    {\n"
    "        const ulong row = i - 1;\n"
    "        const ulong at = row_entry_offset[row];\n"
    "        const ulong count = row_entry_offset[row + 1] - at;\n"
    "        const ulong size_row = block_size(block_offsets, row);\n"
    "        for (ulong t = count; t > 0; --t)\n"
    "        {\n"
    "            const ulong entry = at + t - 1;\n"
    "            const ulong col = entry_col[entry];\n"
    "            if (row >= col)\n"
    "                break;\n"
    "\n"
    "            const ulong size_col = block_size(block_offsets, col);\n"
    "            vec_multiply_sub(vals + entry_val_offset[entry], vec + block_offsets[col],\n"
    "                           vec + block_offsets[row], size_row, size_col, (ulong)1);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* The replay of a recorded operation list: serial there, so serial here. */\n"
    "__kernel void HYBSOL_NAME(apply_ops)(__global const ulong *row_entry_offset,\n"
    "                                          __global const ulong *entry_col,\n"
    "                                          __global const ulong *entry_val_offset,\n"
    "                                          __global const ulong *block_offsets,\n"
    "                                          __global const scalar *vals, __global double *vec,\n"
    "                                          __global const uint *op_type, __global const ulong *op_row,\n"
    "                                          __global const ulong *op_col, const ulong n_ops)\n"
    "{\n"
    "    if (get_global_id(0) != 0)\n"
    "        return;\n"
    "\n"
    "    for (ulong i = 0; i < n_ops; ++i)\n"
    "    {\n"
    "        const ulong row = op_row[i];\n"
    "        const ulong at = row_entry_offset[row];\n"
    "        const ulong count = row_entry_offset[row + 1] - at;\n"
    "        const ulong size_row = block_size(block_offsets, row);\n"
    "        if (op_type[i] == HYBSOL_OP_ELIMINATE)\n"
    "        {\n"
    "            const ulong col = op_col[i];\n"
    "            ulong lo = 0;\n"
    "            ulong hi = count;\n"
    "            while (lo < hi)\n"
    "            {\n"
    "                const ulong mid = lo + (hi - lo) / 2;\n"
    "                if (entry_col[at + mid] < col)\n"
    "                    lo = mid + 1;\n"
    "                else\n"
    "                    hi = mid;\n"
    "            }\n"
    "            const ulong entry = at + lo;\n"
    "            vec_multiply_sub(vals + entry_val_offset[entry], vec + block_offsets[col],\n"
    "                           vec + block_offsets[row], size_row, block_size(block_offsets, col),\n"
    "                           (ulong)1);\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            ulong lo = 0;\n"
    "            ulong hi = count;\n"
    "            while (lo < hi)\n"
    "            {\n"
    "                const ulong mid = lo + (hi - lo) / 2;\n"
    "                if (entry_col[at + mid] < row)\n"
    "                    lo = mid + 1;\n"
    "                else\n"
    "                    hi = mid;\n"
    "            }\n"
    "            const ulong entry = at + lo;\n"
    "            vec_lu_solve(vals + entry_val_offset[entry], vec + block_offsets[row], size_row);\n"
    "        }\n"
    "    }\n"
    "}\n";

#endif /* HYBSOL_OPENCL_GPU_KERNELS_H */
